### ISSUE TITLE
quay.io integration

### ISSUE THREAD

**Issue by tzz** [bahamat/docker-cfengine-policy-hub#4]
I set my fork up to auto-build at quay.io: https://quay.io/repository/tzz_/docker-cfengine-policy-hub

This is free.  You can set up your repo as well, if you wish... I like the notification hooks and badges.

(or close this if you're not interested...)

**Comment by bahamat** [comment]
I have auto build set up with hub.docker.com. Is there a particular advantage to using quay.io, or having it in both?

**Comment by tzz** [comment]
They used to be better back then, now... I'm not sure it's worthwhile.
